name: Build DXF-Doc for Browser

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Webpack
        run: npm install -g webpack webpack-cli

      - name: Clone DXF-Doc and Build
        run: |
          git clone https://github.com/YMSpektor/dxf-doc.git
          cd dxf-doc
          npm install
          npx webpack ./src/index.js -o ./dist/dxf-doc.js --mode production
          cp ./dist/dxf-doc.js ../

      - name: Upload DXF-Doc.js to Repository
        uses: actions/upload-artifact@v3
        with:
          name: dxf-doc
          path: dxf-doc.js
