name: Build DXF-Doc for Browser

on:
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Install Node.js
        uses: actions/setup-node@v4  # Updated to latest version
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install -g typescript webpack webpack-cli

      - name: Clone DXF-Doc and Build
        run: |
          git clone https://github.com/YMSpektor/dxf-doc.git
          cd dxf-doc
          npm install
          
          # Compile TypeScript to JavaScript
          npx tsc

          # Bundle JavaScript into a single file
          npx webpack ./dist/index.js -o ./dist/dxf-doc.js --mode production
          
          # Copy the bundled file to root
          cp ./dist/dxf-doc.js ../dxf-doc.js

      - name: Upload DXF-Doc.js to Artifacts
        uses: actions/upload-artifact@v4  # Updated to latest version
        with:
          name: dxf-doc
          path: dxf-doc.js
