name: Build DXF-Doc for Browser

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Dependencies
        run: |
          npm install -g typescript webpack webpack-cli

      - name: Clone DXF-Doc and Build
        run: |
          git clone https://github.com/YMSpektor/dxf-doc.git
          cd dxf-doc
          npm install
          
          # Compile TypeScript to JavaScript
          npx tsc || echo "TypeScript compilation failed"

          # Ensure the dist directory exists
          mkdir -p dist

          # Check if index.js exists
          if [ ! -f "dist/index.js" ]; then echo "Error: dist/index.js not found"; exit 1; fi

          # Create a Webpack config to bundle everything into one file
          echo 'const path = require("path");
          module.exports = {
            entry: "./dist/index.js",
            output: {
              filename: "dxf-doc.js",
              path: path.resolve(__dirname, "dist"),
              library: "DxfDoc",
              libraryTarget: "umd"
            },
            mode: "production"
          };' > webpack.config.js

          # Run Webpack to bundle everything
          npx webpack --config webpack.config.js || echo "Webpack bundling failed"

          # Verify the bundled file exists
          if [ ! -f "dist/dxf-doc.js" ]; then echo "Error: dist/dxf-doc.js not found"; exit 1; fi

          # Move the bundled file to the root directory
          mv dist/dxf-doc.js ../dxf-doc.js

      - name: Upload DXF-Doc.js to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dxf-doc
          path: dxf-doc.js
